steps:
  # Build the Docker image.
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/docker-spa:$SHORT_SHA', '.']
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/docker-spa:$SHORT_SHA']
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'docker-spa', '--image=eu.gcr.io/$PROJECT_ID/docker-spa:$SHORT_SHA', '--region=europe-west1']